server:
  port: 8088
spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      routes:
        - id: cpic_route
          uri: lb://eureka-client
          predicates:
            - Path=/eureka-client/**
          filters:
            - StripPrefix=2
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:1111/eureka/,http://admin:123456@localhost:1112/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug